export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';

export const ADD_RECIPE = 'ADD_RECIPE'

export const SET_ORDERS = 'SET_ORDERS'

export const SET_ORDERS_SUMMARY = 'SET_ORDERS_SUMMARY'

export const SET_ORDER_SUMMARY_DETAIL = 'SET_ORDER_SUMMARY_DETAIL'

export const SET_ORDER_CARTS = 'SET_ORDER_CARTS'

export const SET_EMPLOYEE_CARTS = 'SET_EMPLOYEE_CARTS'

export const SET_TOKEN = 'SET_TOKEN'

export const RESET_TOKEN = 'RESET_TOKEN'

export const SET_USER = 'SET_USER'

export const RESET_USER = 'RESET_USER'

export const SET_ACCEPTED = 'SET_ACCEPTED'

export const SET_FAIL = 'SET-FAIL'

export const SET_CART_ID = 'SET_CART_ID'